#!/bin/bash

#l

####
# lists the processes sorted by memory usage decreasing
#
# [@param int $1] - number of processes to list (default is 8)
####
# @see https://www.shellhacks.com/find-top-processes-memory-usage-linux/
# @author stev leibelt <artodeto@bazzline.net>
# @since 2021-01-18
####
function net_bazzline_list_memory_usage_by_process ()
{
    local NUMBER_OF_PROCESSES_TO_LIST=${1:-8}

    ps axo rss,comm,pid \
        | awk '{ proc_list[$2]++; proc_list[$2 "," 1] += $1;  } \
    END { for (proc in proc_list) { printf("%d\t%s\n", \
    proc_list[proc "," 1],proc);  } }' | sort -n | tail -n ${NUMBER_OF_PROCESSES_TO_LIST} | sort -rn \
    | awk '{$1/=1024;printf "%.0fMB\t",$1}{print $2}'
}

#s
####
# sets the provided optical drive speed
# 
# @param int $1 - speed (default is 12)
# @param string $2 - path the device (default is /dev/sr0)
# 
# @author stev leibelt <artodeto@bazzline.net>
# @since 2014-12-02
####
function net_bazzline_set_optical_drive_speed ()
{
    net_bazzline_record_function_usage ${FUNCNAME[0]}

    local PATH_TO_THE_DEVICE=${2:-'/dev/sr0'}
    local SPEED=${1:-12}

    eject -x ${SPEED} ${PATH_TO_THE_DEVICE}
}
