#!/bin/bash
#l

####
# This is only working of you have a swap space configured, else it will just display 0 KB.
#
# @see:https://www.cyberciti.biz/faq/linux-which-process-is-using-swap/
####
function net_bazzline_list_biggest_swap_space_consumers
{
    for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | sort -k 2 -n -r | less
}
