#!/bin/bash
####
# Central file containing logic when to source what file how
####
# @author stev leibelt <artodeto@bazzline.net>
# @since 2013-04-24
####

function net_bazzline_shell_config_bootstrap ()
{
    # order is important
    # path starting with _source/ are handled differently
    #   it is assumed that this are more complex with a dedicated autoloading
    declare -a SECTIONS_TO_LOAD=(
        'setting'
        'variable'
        'source'
        'export'
        '_source/function/bootstrap'
        '_source/alias/bootstrap'
        'automatic_start'
    )

    # automatic loads files and optional existing local.* files
    for SECTION_TO_LOAD in ${SECTIONS_TO_LOAD[@]}; do
        #determine section type
        if [[ "${SECTION_TO_LOAD}" = "_source/"* ]]; #if SECTION_TO_LOAD starts with _source/
        then
            local SECTION_NAME=${SECTION_TO_LOAD:8:-10}    #returns the part between "_source/" and "/bootstrap"

            source "${PATH_SHELL_CONFIG}/${SECTION_TO_LOAD}"
            local LOCAL_LEGACY_SECTION_TO_LOAD="${SECTION_NAME}.local"
            local LOCAL_SECTION_TO_LOAD="local.${SECTION_NAME}"
        else
            source "${PATH_SHELL_CONFIG}/${SECTION_TO_LOAD}"
            local LOCAL_LEGACY_SECTION_TO_LOAD="${SECTION_TO_LOAD}.local"
            local LOCAL_SECTION_TO_LOAD="local.${SECTION_TO_LOAD}"
        fi

        #loading files
	#section can be removed 2021-10-06
        if [[ -f "${PATH_SHELL_CONFIG}/${LOCAL_LEGACY_SECTION_TO_LOAD}" ]];
        then
            echo ":: Legacy local file name detected, please rename it to ${LOCAL_LEGACY_SECTION_TO_LOAD}"

	    if [[ -f ${PATH_SHELL_CONFIG}/${LOCAL_SECTION_TO_LOAD} ]];
	    then
		echo "   File already exists, can not rename legacy file to >>${PATH_SHELL_CONFIG}/${LOCAL_SECTION_TO_LOAD}<<"
	    else
		mv -v "${PATH_SHELL_CONFIG}/${LOCAL_LEGACY_SECTION_TO_LOAD}" "${PATH_SHELL_CONFIG}/${LOCAL_SECTION_TO_LOAD}"
	    fi
        fi

        if [[ -f "${PATH_SHELL_CONFIG}/${LOCAL_SECTION_TO_LOAD}" ]];
        then
            source "${PATH_SHELL_CONFIG}/${LOCAL_SECTION_TO_LOAD}"
        fi
    done;
}

net_bazzline_shell_config_bootstrap
