#!/bin/bash
####
# @author stev leibelt <artodeto@bazzline.net>
# @since 2013-04-24
####

#e
export EDITOR="vim"

#h
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:top:ps:exit:date"
export HISTSIZE=20
export HISTFILESIZE=$HISTSIZE

#l
#@see: https://opensource.com/article/18/5/advanced-use-less-text-file-viewer
export LESS='-C -M -I -j 10'

#t
export TERM=xterm-256color
