#!/bin/bash
####
# @author stev leibelt <artodeto@bazzline.net>
# @since 2013-04-24
####

#d - disables also powershell foo from ~/.cache/powershell/telemetrie.uuid
export DOTNET_CLI_TELEMETRY_OPTOUT=1

#e
export EDITOR="vim"

#h
#@see: https://opensource.com/article/18/7/admin-guide-bash
#ignore command starting with a space and only keep a command in once
export HISTCONTROL=ignorespace:erasedups
export HISTIGNORE="ls:cd:top:ps:exit:date"
export HISTSIZE=20
export HISTFILESIZE=40
#prepend all entries with a timestamp YYYY-MM-DD\ HH:MM:SS
export HISTTIMEFORMAT="%F %T  "

#l
#@see: https://opensource.com/article/18/5/advanced-use-less-text-file-viewer
export LESS='-C -M -I -j 10'

#p
#usefull for things like python or Jetbrains toolbox script generation
export PATH=$PATH:${HOME}/.local/bin

#t
#@see: https://wiki.archlinux.org/title/Xterm
export TERM=xterm-256color
