#!/bin/bash
####
# Used to configure used software like
#   * this project
#   * bash
#   * grep
#   * ssh
#   * vim
####
# @author stev leibelt <artodeto@bazzline.net>
# @since 2013-04-24
####

#https://wiki.archlinux.org/index.php/Xterm#TERM_Environmental_Variable
#export GREP_OPTIONS='--color=auto'
#https://bbs.archlinux.org/viewtopic.php?pid=1478573
unset GREP_OPTIONS

export LESS=-R
export LESS_TERMCAP_me=$(printf '\e[0m')
export LESS_TERMCAP_se=$(printf '\e[0m')
export LESS_TERMCAP_ue=$(printf '\e[0m')
export LESS_TERMCAP_mb=$(printf '\e[1;32m')
export LESS_TERMCAP_md=$(printf '\e[1;34m')
export LESS_TERMCAP_us=$(printf '\e[1;32m')
export LESS_TERMCAP_so=$(printf '\e[1;44;1m')

#start ssh agent (if available), valid values are 0 and 1
NET_BAZZLINE_AUTOSTART_SSH_AGENT=0
#either you are using an lts kernel or not: uname -a | grep -i lts
NET_BAZZLINE_IS_LTS_KERNEL=1
#add all you known interfaces in here
NET_BAZZLINE_INTERFACES=()
#allowed are [apk, apt, none, pacman, pacget]
NET_BAZZLINE_PACKAGE_MANAGER='none'
#either write statistics of function usage or not
#1 turns it on, all other values disables it
NET_BAZZLINE_RECORD_FUNCTION_USAGE=0
#timeout in minutes to forget ssh password
NET_BAZZLINE_REMEMBER_SSH_PASSWORD_TIMEOUT_IN_MINUTES=30
#add port where your secure connection is listen on (via ssh -D)
NET_BAZZLINE_SECURE_CONNECTION_PORT=0
#enables (1) or disabled (0) zfs support
if [[ -f /usr/bin/zpool ]];
then
    NET_BAZZLINE_ZFS_AVAILABLE=1
else
    NET_BAZZLINE_ZFS_AVAILABLE=0
fi
#default zfs pool if non is provided
NET_BAZZLINE_ZFS_DEFAULT_POOL='zpool'

#https://wiki.archlinux.org/index.php/Bash
# faster completion
set show-all-if-ambiguous on
set show-all-if-unmodified on

#arrow keys in 8 bit ANSI mode
#bind "\e[C": forward-word
#bind "\e[D": backward-word

####
#@see: https://opensource.com/article/18/5/bash-tricks
#allow bash history for multiple users
shopt -s histappend
#enable spell support to guess/correct "/tpm" to "/tmp"
shopt -s cdspell
#enable colors
eval "`dircolors -b`"
####
