#!/bin/bash
####
# @author stev leibelt <artodeto@bazzline.net>
# @since 2013-04-24
####

#https://wiki.archlinux.org/index.php/Xterm#TERM_Environmental_Variable
#export GREP_OPTIONS='--color=auto'
#https://bbs.archlinux.org/viewtopic.php?pid=1478573
unset GREP_OPTIONS

export LESS=-R
export LESS_TERMCAP_me=$(printf '\e[0m')
export LESS_TERMCAP_se=$(printf '\e[0m')
export LESS_TERMCAP_ue=$(printf '\e[0m')
export LESS_TERMCAP_mb=$(printf '\e[1;32m')
export LESS_TERMCAP_md=$(printf '\e[1;34m')
export LESS_TERMCAP_us=$(printf '\e[1;32m')
export LESS_TERMCAP_so=$(printf '\e[1;44;1m')

#allowed are [apt, none, pacman, yaourt]
NET_BAZZLINE_PACKAGE_MANAGER='none'
#add all you known interfaces in here
NET_BAZZLINE_INTERFACES=()
