#!/bin/bash
####
# @author stev leibelt <artodeto@bazzline.net>
# @since 2013-04-24
####

if [ -f ~/data/git/com/github/nojhan/liquidprompt/liquidprompt ]; then
  source ~/data/git/com/github/nojhan/liquidprompt/liquidprompt
fi
