#!/bin/bash
####
#
####
# @since 2018-06-03
# @author stev leibelt
####

function net_bazzline_shell_config_function_bootstrap ()
{
    local PATH_OF_THE_CURRENT_SCRIPT=$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)

    #order is important
    #@todo each section should have its own bootstrap
    declare -a FILES_TO_LOAD=(
        'device/generic'
        'function' 
        'filesystem/generic' 
        'filesystem/luks' 
        'media/audio' 
        'media/book'
        'media/generic' 
        'media/image' 
        'media/video' 
        'network/generic' 
        'network/ssh' 
        'process/generic' 
        'packagemanager/generic' 
        'string/generic'
    )

    if [[ ${NET_BAZZLINE_ZFS_IS_AVAILABLE} -eq 1 ]];
    then
        FILES_TO_LOAD+=('filesystem/zfs')
    fi

    if [[ ${NET_BAZZLINE_OPERATION_SYSTEM_IS_WINDOWS} -eq 1 ]];
    then
        FILES_TO_LOAD+=('filesystem/windows')
    fi

    for FILE_TO_LOAD in ${FILES_TO_LOAD[@]};
    do
        source "${PATH_OF_THE_CURRENT_SCRIPT}/${FILE_TO_LOAD}"
    done;
}

net_bazzline_shell_config_function_bootstrap
