---
- name: Update system using yay
  hosts: localhost
  tasks:
    - name: Call yay
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        aur_only: no
        update_cache: true
        upgrade: true
        use: yay
