#!/bin/bash

#c
alias createSha512sumFromFile=net_bazzline_filesystem_create_sha512sum_from_file

#f
alias fixQuotes=net_bazzline_filesystem_generic_fix_quotes

#l
alias listBiggestSwapSpaceConsumers=net_bazzline_filesystem_list_biggest_swap_space_consumers
alias listBiggestDirectories=net_bazzline_filesystem_list_biggest_directories
